unique_ids:
  assets:
    standard-page.html: NZ25OKEGDHDVNNDH7K5HOXYKSKFRR4D5
    theme.css: PRZPFHT25VXHOJWIJLNEG7Q4GB3BUVMU
  forms:
    Form1: OEXKDJV23W4VBP4EZICJ47R3NVOKAWZ7
  modules: {}
  scripts: {}
  server_modules: {}
